### ISSUE TITLE
Webbased Nextcloud updater fails in reverse proxy scenario with / vs. /something

### ISSUE THREAD

**Issue by robert-scheck** [nextcloud/updater#265]
### Steps to reproduce
1. Get Nextcloud 11.0.1
2. `./occ maintenance:install --data-dir=/var/www/html/data --database mysql --database-name nextcloud --database-user nextcloud --database-pass nextcloud --admin-user admin --admin-pass admin`
3. Ensure the setup works at http://localhost/ as expected
4. Put a reverse proxy called `tux.example.net` in front of it – including HTTPS
5. Ensure that Nextcloud is installed on `/`, but access using reverse proxy happens via `/my-nextcloud`
6. Visit https://tux.example.net/my-nextcloud/settings/admin
7. Press "Start update" button
8. Receive "Check for expected files: Parsing response failed. […]"
9. Figure out that the POST request went to https://tux.example.net/updater/index.php rather https://tux.example.net/my-nextcloud/updater/index.php

### Expected behaviour
Webbased Nextcloud updater fails in reverse proxy scenario with / vs. /something

### Actual behaviour
Properly working webbased Nextcloud updater even in reverse proxy scenario with / vs. /something

### Server configuration
**Operating system**: Red Hat Enterprise Linux 7.3, but doesn't matter here anyway.

**Web server:** Apache Webserver 2.4, but doesn't matter here anyway.

**Database:** MariaDB 5.5, but doesn't matter here anyway.

**PHP version:** 7.1 (via Remi Safe repository), but doesn't matter here anyway.

**Nextcloud version:** 11.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh installation.

**Where did you install Nextcloud from:**  https://download.nextcloud.com/server/releases/nextcloud-11.0.1.tar.bz2

**Signing status:** N/A

**List of activated apps:** N/A

**The content of config/config.php:**
```
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => 'tux.example.net',
  ),
  'overwrite.cli.url' => 'https://tux.example.net/my-nextcloud',
  'overwritehost' => 'tux.example.net',
  'overwriteprotocol' => 'https',
  'overwritewebroot' => '/my-nextcloud',
  'trusted_proxies' => 
  array (
    1 => '172.17.0.1',
  ),
  'overwritecondaddr' => '^172\\.17\\.0\\.1$',
  'htaccess.RewriteBase' => '/',
```

**Are you using external storage, if yes which one:** No external storage.

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

**Comment by Pleune** [comment]
I just ran into this with my server running on my domain under `/cloud`, and my workaround was to open the chrome tools (F12) and search the page for `/updater`. There were two links that I changed to instead start with `/cloud/updater`. After this, the updater worked as it should.

**Comment by robert-scheck** [comment]
I wonder why upstream is not interested in fixing this even after 3+ years now…

**Comment by zeigerpuppy** [comment]
This would be really helpful to fix.  It may also be a good feature to have a flag to disable the web updater for anyone having this issue.

**Comment by fermulator** [comment]
>  It may also be a good feature to have a flag to disable the web updater for anyone having this issue.
not sure about that feature idea though, what would be the benefit? - just fix it;

**Comment by zeigerpuppy** [comment]
disabling the web updater can also be useful in a setting where there is more than one admin and  the administrator responsible for updates wants to do these via the command line only.

**Comment by fermulator** [comment]
> disabling the web updater can also be useful in a setting where there is more than one admin and the administrator responsible for updates wants to do these via the command line only.

got it; :+1: that is a separate issue though, let's not conflate this one;  suggest submitting a feature request for it

**Comment by syqe** [comment]
Still present on 18.0.4

**Comment by khampf** [comment]
Present in 19.0.2. Irritating as I can not get the CLI updater to work (even if occ does)

**Comment by robert-scheck** [comment]
After 3.5+ years, the conclusion seems to be that implementing new fancy features seems to be more interesting for developers rather fixing old nasty bugs…

**Comment by khampf** [comment]
I discovered I could get the proxied server to start updating by tunnelling in behind the proxy but then the web updater still broke on gateway timeouts perhaps due to other reasons. After some fiddling about I then got the CLI updater to do its job so problem solved in some way at least - I have been doing manual upgrades for years

**Comment by pgaufillet** [comment]
An easy workaround is to configure an specific reverse proxy for the updater. E.g. with Apache something like:

 ```
              <Location "/updater">
                      ProxyPass "http://<internal_address>/updater"
                      ProxyPassReverse "http://<internal_address>/updater"
                      ProxyPassReverseCookieDomain  "<internal_address>" "<external_address>"
                      ProxyPassReverseCookiePath  "/"  "/nextcloud/"
                </Location>

```
if the reverse proxy is `http://<external_address>/nextcloud` and the internal nextcloud server is `http://<internal_address>`

**Comment by fermulator** [comment]
the workaround in dev tools in your browser is quite handy
https://github.com/nextcloud/updater/issues/265#issuecomment-619125866

there were only two URLs in the updater to tweak

**Comment by fermulator** [comment]
implemented a fix ^^ #312 ! - please give it some review

**Comment by kreutpet** [comment]
i downloaded both files from the #312 and replaced the old files.
still get the following  
Error | internet_connection_check | GuzzleHttp\Exception\ConnectException: cURL error 28: Connection timed out after 30001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
-- | -- | --

i set log level to 0 , but i did not get any additional info.
any hints what i can check on my site.
```
sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.204",
            "MYDOMAIN.COM"
        ],
        "proxy": "192.168.1.253",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "MYDOMAIN.COM",
        "overwrite.cli.url": "https:\\MYDOMAIN.COM",
        "overwriteprotocol": "https",
        "overwritecondaddr": "^192\\.168\\.1\\.204$",
        "dbtype": "mysql",
        "version": "20.0.1.1",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "log_type": "file",
        "logfile": "\/var\/www\/html\/data\/nextcloud.log",
        "loglevel": 3,
        "log_rotate_size": 104857600,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "appstore.experimental.enabled": true,
        "updatechecker": false,
        "updater.release.channel": "stable",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "mail_sendmailmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "app_install_overwrite": [
            "calendar"
        ]
    }
}
```

**Comment by fermulator** [comment]
@kreutpet  - can you confirm a few things for me
1. where did you update/save the files from the PR? for me:
```
fermulator@nextcloud:/srv/nextcloud/updater$ ll
total 664
drwxrwx---+  2 www-data www-data   4096 Nov 21 13:58 ./
drwxrwx---+ 13 www-data www-data   4096 Nov 21 13:57 ../
-rw-r--r--   1 www-data www-data  65805 Nov 21 13:56 index.php
-rw-r--r--   1 www-data www-data 600602 Nov 21 13:56 updater.phar
```

2. after you've applied those changes/fixes (and confirmed), please re-open the updater completely (start at Nextcloud, Settings, Overview, click "Open updater") -- then verify via dev tools what the "/updater" values are on the page? https://github.com/nextcloud/updater/issues/265#issuecomment-619125866 <-- see this comment for how

**Comment by kreutpet** [comment]
1.
the first file went here
/var/www/html/updater# ls -l
total 474
-rw-r----- 1 www-data www-data  67058 Dec 13 15:03 index.php
-rw-r----- 1 www-data www-data 600659 Oct 24 10:38 updater.phar

should this .phar archive also been updated or is this done automatically? 

second file here
/var/www/html/lib/private# ls -l Updater.p*
-rw-r----- 1 www-data www-data 35469 Dec 13 15:07 Updater.php

2.
searched in the dev tool in chrome found this in 
https://mydomain.com/apps/updatenotification/js/updatenotification.js?v=49cb2a33-15
373				form.setAttribute('action', getRootUrl() + '/updater/')

3.
no new log entry created

**Comment by fermulator** [comment]
@kreutpet , 
1. the fix assumes a REVERSE proxy, you do not have `overwritewebroot` set in your configuration (but you do have `proxy` set), so I think maybe your setup is a FORWARD proxy?
2. those errors about "no internet" is a different problem possibly in your setup, please take that up elsewhere

**Comment by kreutpet** [comment]
1
the webroot is /var/www/html 
not aware that i need to use it 
how should is use it?

2
well i looked already elsewhere and all was not working.
 
my update worked until 18.0.2.2.
not sure why i am not getting any update anymore via web updater.
again i checked my proxy configuration 
also here i can not find any missconfuguration

```
<IfModule mod_ssl.c>
<VirtualHost *:443>
        ServerName MYDOMAIN.COM
        ProxyPreserveHost On
        DocumentRoot /var/www/html
        <IfModule mod_headers.c>
          Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains"
          Redirect 301 /.well-known/carddav /remote.php/dav
          Redirect 301 /.well-known/caldav /remote.php/dav
        </IfModule>

        SSLProxyEngine on
        ProxyPass /.well-known !

        ProxyPass / http://192.168.1.204:80/
        ProxyPassReverse / http://192.168.1.204:80/
        ProxyPassReverseCookiePath / /

        Include /etc/letsencrypt/options-ssl-apache.conf

        SSLCertificateFile /etc/letsencrypt/live/MYDOMAIN.COM/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/MYDOMAIN.COM/privkey.pem

</VirtualHost>
</IfModule>
```
could you answer my question related to updater.phar and if i updated the right files

**Comment by fermulator** [comment]
@kreutpet  please submit a separate issue; (your configuration does not match this issue)

**Comment by freakinpenguin** [comment]
I'm having troubles to find the correct files for the fix mentioned above. This might be due to the fact that this issue is already open for such a long time (I'm running nextcloud 20.0.4).
In particular my directory structure is different. My Updater.php is located in the subfolder lib/private. In there is also a directory named Updater with the following content:
- hangesCheck.php
-   ChangesMapper.php
-   ChangesResult.php
-   VersionCheck.php

I don't know which index.php to update - can anyone give me a hint?

**Comment by fermulator** [comment]
> I don't know which index.php to update - can anyone give me a hint?
@freakinpenguin 

I see:
```
fermulator@nextcloud:/srv/nextcloud$ find . | grep ChangesCheck
./lib/private/Updater/ChangesCheck.php
```
, you actually want:
```
fermulator@nextcloud:/srv/nextcloud$ find . | grep updater/index
./updater/index.php
```

you should have an `updater` directory there

**Comment by freakinpenguin** [comment]
> 
> 
> > I don't know which index.php to update - can anyone give me a hint?
> > @freakinpenguin
> 
> I see:
> 
> ```
> fermulator@nextcloud:/srv/nextcloud$ find . | grep ChangesCheck
> ./lib/private/Updater/ChangesCheck.php
> ```
> 
> , you actually want:
> 
> ```
> fermulator@nextcloud:/srv/nextcloud$ find . | grep updater/index
> ./updater/index.php
> ```
> 
> you should have an `updater` directory there

Thanks for your help! 

I realized that my issue was that I'm using a docker container. For docker containers the update procedure is described on the docker page (https://hub.docker.com/_/nextcloud/) and it seams that the updater is not delivered within the docker image.

Nevertheless, the button to update is still available in the docker-image version - that's what confused me and what should be changed IMHO.

**Comment by Lulaschkas** [comment]
I can agree that this bug is still present. (but after manually changing the /updater/index.php path to /subdir/updater/index.php path in the webupdater it works.)

**Comment by fermulator** [comment]
Ya but we have to do this for EVERY update ....

**Comment by adam-op** [comment]
wow, open since 2017, i will stick to command line then :)

**Comment by adam-op** [comment]
> I can agree that this bug is still present. (but after manually changing the /updater/index.php path to /subdir/updater/index.php path in the webupdater it works.)

Hi @Lulaschkas 

could you please provide steps what does it mean "manually change"
where do you change that?

thank you

**Comment by fermulator** [comment]
> 

F12 in browser, then find-replace `/updater` as needed for your particular proxy scenario

**Comment by adam-op** [comment]
thank you, could please provide an example for your particular proxy scenario

i think i will not need to replace /updater by "as needed for your particular proxy scenario"
but that is what is written at the moment...

**Comment by fermulator** [comment]
@adam-op  - here's my situation (and a common one for reverse proxy)
* nextcloud hosted at URI: https://<your-domain>/nextcloud
* go to the updater https://<your-domain>/nextcloud/updater/
* hit F12 (dev tools)
* find `/updater`, and for me I replace all instances of that with `/nextcloud/updater`
* then proceed with the update

without this, the updater doesn't work

**Comment by fermulator** [comment]
I had a fix and PR >2 years ago Nov2020 ... but maintainers haven't been active enough to provide reasons/direction into what they want the "right" fix to be

**Comment by fermulator** [comment]
Just finished testing the fix in #448 nice work @kesselb  -- LGTM! ✅  - once reviewers verify/finish that code is functional and solves the reverse proxy scenario 🎉

**Comment by adam-op** [comment]
will this be released in 25.x or forgotten again :) ? i am really waiting for this since start of using Nextcloud. Thank you!

**Comment by robert-scheck** [comment]
Wow, finally fixed after 6+ years…thank you @kesselb!
